linters:
  enable:
    - gofmt
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - ineffassign
    - unused
    - misspell
    - gocyclo
    - gosec
    - bodyclose
    - gocritic
    - gocognit
    - goconst
    - goimports
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - staticcheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace

run:
  timeout: 5m
  tests: true
  skip-dirs:
    - vendor

linters-settings:
  gocyclo:
    min-complexity: 15
  goconst:
    min-len: 3
    min-occurrences: 3

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - gosec

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true 