name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21'

    - name: Build
      run: |
        GOOS=linux GOARCH=amd64 go build -o askllm-linux-amd64
        GOOS=linux GOARCH=arm64 go build -o askllm-linux-arm64
        GOOS=linux GOARCH=arm go build -o askllm-linux-armv7
        GOOS=darwin GOARCH=amd64 go build -o askllm-darwin-amd64
        GOOS=darwin GOARCH=arm64 go build -o askllm-darwin-arm64

    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          askllm-linux-amd64
          askllm-linux-arm64
          askllm-linux-armv7
          askllm-darwin-amd64
          askllm-darwin-arm64
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 