name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21'
        cache: true

    - name: Download dependencies
      run: go mod download

    - name: Build
      run: |
        mkdir -p dist
        GOOS=linux GOARCH=amd64 go build -o dist/askllm-linux-amd64
        GOOS=linux GOARCH=arm64 go build -o dist/askllm-linux-arm64
        GOOS=linux GOARCH=arm GOARM=7 go build -o dist/askllm-linux-armv7
        GOOS=darwin GOARCH=amd64 go build -o dist/askllm-darwin-amd64
        GOOS=darwin GOARCH=arm64 go build -o dist/askllm-darwin-arm64

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          dist/askllm-linux-amd64
          dist/askllm-linux-arm64
          dist/askllm-linux-armv7
          dist/askllm-darwin-amd64
          dist/askllm-darwin-arm64
        draft: false
        prerelease: false
        generate_release_notes: true 